### ISSUE TITLE
Whats the license

### ISSUE THREAD

**Issue by dano1066** [TheArtificial/pokemon-icons#32]
Just wondering what the copyright license is for these icons. Are they free to use on websites?

**Comment by shankarsivarajan** [comment]
From the [README](https://github.com/TheArtificial/pokemon-icons/blob/master/_icons/README):
"We created this fan are from scratch, and because we share our public work as **CC-BY** [emphasis mine] we don't mind if you share them as long as you give us credit. Of course we respect others' trademarks and can't indemnify or give you any special rights, so if you want to publish something involving Pokémon characters, you ought to study up and get some legal advice."

**Comment by gerwitz** [comment]
In short: they are intentionally unlicensed and you use or republish them entirely at your own risk.

We shared the initial set with the world as public domain fan art only. We do not presume we have the right to license it, because in using Pokemon names it references trademarks of TPCI. In fact, they threatened to sue our agency simply for publishing them. (I should say that I empathize with their position. If you allow other parties to attach licenses to your IP, you risk invalidating your own claims.)
